# rule identifiers turned on by default to exclude from running
disabled_rules:
  - identifier_name
  - line_length
  
identifier_name:
  min_length: # only min_length
    error: 2 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
    
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
